### ISSUE TITLE
Create blank slate / templated frontend

### ISSUE THREAD

**Issue by aiden-gonzalez** [lanterndevs/Lantern-Client#4]
Set up a nearly empty frontend application using the agreed-upon languages/technologies.  Pick a popular and well-supported automated testing framework (could be something built-in to React or at least easy to add) and write a few basic tests to get us started!

**Comment by oogunjob** [comment]
Dashboard template has been committed to dev branch and still in development progress

**Comment by aiden-gonzalez** [comment]
Complete
