### ISSUE TITLE
Update Financial Accounts/Transactions Pages for Compatibility with Plaid

### ISSUE THREAD

**Issue by oogunjob** [lanterndevs/Lantern-Client#8]
As we look to integrate the use of Plaid in our software, we need to ensure we have front-end components that can visually display the information received from Plaid's API. Financial Accounts page should allow users to add and view the accounts connected with Plaid. Transactions page should populate with a list of transactions pulled from connected account(s)

**Comment by aiden-gonzalez** [comment]
Complete
